server:
  port: 8000

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.31.58:8848

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml #mybatis的sql映射文件位置
  global-config:
    db-config:
      id-type: auto

