server:
  port: 7200

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.31.58:8848


#mybatis的sql映射文件位置
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
